
CREATE TABLE IF NOT EXISTS T_ORDER_0 (order_id BIGINT AUTO_INCREMENT, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS T_ORDER_1 (order_id BIGINT AUTO_INCREMENT, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS T_ORDER_ITEM_0 (order_item_id BIGINT AUTO_INCREMENT, order_id BIGINT, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (order_item_id));
CREATE TABLE IF NOT EXISTS T_ORDER_ITEM_1 (order_item_id BIGINT AUTO_INCREMENT, order_id BIGINT, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (order_item_id));


DROP TABLE IF EXISTS T_ORDER_ITEM_0;
DROP TABLE IF EXISTS T_ORDER_ITEM_1;
DROP TABLE IF EXISTS T_ORDER_0;
DROP TABLE IF EXISTS T_ORDER_1;